---
  - hosts: cisco
    gather_facts: no

    tasks:

      - name: Create configuration templates
        template:
          src: "templates/{{ ansible_network_os }}_bgp.j2"
          dest: "configs/{{ inventory_hostname }}.config"

      - name: load BGP config eos
        ios_config:
          src: "configs/{{ inventory_hostname }}.config"
        register: updates

      - name: debug updates
        debug:
          msg: "{{ updates.updates }}"
