---
- name: checking device reachability
  hosts: juniper
  connection: local
  gather_facts: yes
  tasks:
# Simple example
     - name: Test reachability to 10.10.10.10
       junos_ping:
         dest: 10.10.10.10

   # - name: Test reachability to 10.20.20.20 using source and size set
   #   junos_ping:
   #    dest: 10.20.20.20
    #   size: 1024
   #    ttl: 128

   # - name: Test unreachability to 10.30.30.30 using interval
   #   junos_ping:
  #     dest: 10.30.30.30
   #    interval: 3
   #    state: absent
   
