---
- name: Gather extensive details for fxp0 interfaces that are UP
  hosts: juniper
  connection: local
  gather_facts: no
  tasks:
  - name: Gather all fxp0 interfaces status
    junos_command:
      commands:
        - show interfaces terse fxp0
      #provider: "{{ credential }}"
    register: result

  - debug: var=result.stdout

  - name: Collect extensive information for interfaces fxp0 if Up
    junos_command:
      commands:
        - show interfaces fxp0 extensive
     # provider: "{{ credential }}"
    register: int
   - debug: var=int.stdout   