---
- name: configure the cisco banner 
  ##Playbook to configure the banner##
  hosts: cisco
  connection: local
  become_method: enable
    
  tasks:
    - name: GET DEVICE FACTS
      ios_facts:
      
    - name: configure the login banner 
    #for configure the login banner#
      ios_banner:
       banner: login
       text: |
               -----------------------------------------------------------------------

                      This is a private network. No unauthorised access

                      If you are not authorised to use this equipment you must

                                   DISCONNECT IMMEDIATELY

               ----------------------------------------------------------------------- 
       state: present
    - name: Configure motd banner  
    #for configure the motd banner#
      ios_banner:
       banner:  motd
       text: |
               -----------------------------------------------------------------------
                         #Unauthorized access to this device is prohibited!#
               -----------------------------------------------------------------------
          
       state: present  
 
   # - name: remove the motd banner 
    #for remove the motd banner#
   #   ios_banner:
  #     banner: motd
   #    state: absent

  # - name: deactivate the motd banner 
   #for deactivate the motd banner#
  #   ios_banner:
   #   banner: motd
   #   state: present
   #   active: False

   # - name: activate the motd banner  
   #for activate the motd banner#
    #  ios_banner:
    #   banner: motd
    #   state: present
    #   active: True       
