---
- name: Configure interface on cisco Router R1
    #This Playbook will be use to configure and management interfaces on cisco Router
  hosts: R1
  connection: local
  gather_facts: no
  tasks:
    - name: configure interface on R1 Router for FastEthernet1/0 interface
      ios_interface:
       name: FastEthernet1/0
       description: test-interface configure from RedHat Ansible
       speed: 100
       duplex: half
       mtu: 512

    - name: configure IP address to R1 FastEthernet1/0
      ios_config:
         lines:
          - ip address 54.0.0.1  255.255.255.0
         parents: interface FastEthernet1/0


    - name: make interface down for R1 for FastEthernet1/0
      ios_interface:
       name: FastEthernet1/0
       enabled: False

    - name: make interface up for R1 for FastEthernet1/0
      ios_interface:
        name: FastEthernet1/0
        enabled: True
