---
- name: Get Device Facts
  hosts: juniper
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: Retrieve facts from device running Junos OS
      juniper_junos_facts:
        host: "{{ inventory_hostname }}"
        passwd: getpass("Device password: ")
        savedir: "{{ playbook_dir }}"
    - name: Print version
      debug:
        var: junos.version