---
- name: Get Junos facts from vMX router
  hosts: juniper
  connection: local
  gather_facts: no
  tasks:
    - name: gather junos_facts
      junos_facts:
      register: version

    - debug:
        msg: "{{version}}"

    - name: collect default set of facts and configuration
      junos_facts:
        gather_subset: config
