---
- name: Get Junos facts from vMX router
  hosts: juniper
  connection: local
  gather_facts: no
  tasks:
    - name: Ping 10.0.20.2 with default parameters. Fails if any packets lost.
      juniper_junos_ping:
        dest: "10.0.20.2"
    - name: gather junos_facts
      junos_facts:
      register: version

    - debug:
        msg: "{{version}}"

    - name: collect default set of facts and configuration
      junos_facts:
        gather_subset: config
