---
- name: Get device information
  hosts: juniper
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: Get software and system uptime information
      juniper_junos_rpc:        
        rpcs: 
          - "get-software-information"        
          - "get-system-uptime-information"
        formats: "text"
      register: junos_result

    - name: Print response
      debug:
        var: junos_result