---
- name: Get Junos facts from vMX router
  hosts: juniper
  connection: local
  gather_facts: yes
  tasks:
    - name: configure the login banner
      junos_banner:
       banner: login
       text: |
        This is vMX_vpc server
       state: present
    