---
  - hosts: R4
    gather_facts: no
    tasks:
      - name: configure loopback interface on R4 Router for loopback1 interface
        ios_interface:
         name: loopback1
         description: loopback1 configure from RedHat Ansible.
      
      - name: configure IP address to R4 loopback
        ios_config:
          lines:
           - ip address 4.4.4.4  255.255.255.0
          parents: interface loopback1
