---
  #This Playbook will be use to configure and management interfaces on cisco Router
  - hosts: R1
    connection: local
    gather_facts: no
    tasks:
      - name: configure interface on R1 Router for FastEthernet1/0 interface
        ios_interface:
         name: FastEthernet1/0
         description: FastEthernet1/0 configure from RedHat Ansible.
         speed: 100
         duplex: half
         mtu: 512

      - name: configure IP address to R1 FastEthernet1/0
        ios_config:
          lines:
           - ip address 54.0.0.1  255.255.255.0
          parents: interface FastEthernet1/0

  - hosts: R2
    gather_facts: no
    tasks:
      - name: configure interface on R2 Router for FastEthernet1/0 interface
        ios_interface:
         name: FastEthernet1/0
         description: FastEthernet1/0 configure from RedHat Ansible.
         speed: 100
         duplex: half
         mtu: 512

      - name: configure IP address to R2 FastEthernet1/0
        ios_config:
          lines:
           - ip address 64.0.0.1  255.255.255.0  
          parents: interface FastEthernet1/0


  - hosts: R3
    gather_facts: no
    tasks:
      - name: configure interface on R3 Router for FastEthernet1/0 interface
        ios_interface:
         name: FastEthernet1/0
         description: FastEthernet1/0 configure from RedHat Ansible.
         speed: 100
         duplex: half
         mtu: 512

      - name: configure IP address to R3 FastEthernet1/0
        ios_config:
          lines:
           - ip address 74.0.0.1  255.255.255.0
          parents: interface FastEthernet1/0

  - hosts: R4
    gather_facts: no
    tasks:
      - name: configure interface on R4 Router for FastEthernet1/0 interface
        ios_interface:
         name: FastEthernet1/0
         description: FastEthernet1/0 configure from RedHat Ansible.
         speed: 100
         duplex: half
         mtu: 512

      - name: configure IP address to R4 FastEthernet1/0
        ios_config:
          lines:
           - ip address 84.0.0.1  255.255.255.0
          parents: interface FastEthernet1/0
