---
  #This Playbook will be use to configure and management interfaces on cisco Router
  - hosts: R1
    connection: local
    gather_facts: no
    tasks:
      - name: configure interface on R1 Router for loopback0 interface
        ios_interface:
         name: loopback00
         description: loopback0 configure from RedHat Ansible.

      - name: configure IP address to R1 loopback0
        ios_config:
          lines:
           - ip address 1.1.1.1 255.255.255.255
          parents: interface loopback0

  - hosts: R2
    gather_facts: no
    tasks:
      - name: configure interface on R2 Router for loopback0 interface
        ios_interface:
         name: loopback0
         description: loopback0 configure from RedHat Ansible.

      - name: configure IP address to R2 loopback0
        ios_config:
          lines:
           - ip address 2.2.2.2 255.255.255.255
          parents: interface loopback0


  - hosts: R3
    gather_facts: no
    tasks:
      - name: configure interface on R3 Router for loopback0 interface
        ios_interface:
         name: loopback0
         description: loopback0 configure from RedHat Ansible.

      - name: configure IP address to R3 loopback0
        ios_config:
          lines:
           - ip address 3.3.3.3 255.255.255.255
          parents: interface loopback0

  - hosts: R4
    gather_facts: no
    tasks:
      - name: configure interface on R4 Router for loopback0 interface
        ios_interface:
         name: loopback0
         description: loopback0 configure from RedHat Ansible.

      - name: configure IP address to R4 loopback0
        ios_config:
          lines:
           - ip address 4.4.4.4 255.255.255.255
          parents: interface loopback0
