---
- name: backup router configurations
  hosts: cisco
  connection: local
  gather_facts: no
  tasks:
      - name: Backup eos device
        ios_config:
          backup: yes
        register: "{{ inventory_hostname }}"
