---
- name: backup router configurations
  hosts: juniper 
  connection: local
  gather_facts: no
  tasks:
    - name: gather JUNOS_facts
      junos_facts:
      register: version

    - debug:
        msg: "{{version}}"

    - name: Backup configuration
      junos_config:
        backup: yes
